name: Publish Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  buildRelease:
    name: Build Release APK
    runs-on: ubuntu-22.04

    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK environment
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Setup APK signing
        run: |
          mkdir -p app
          printf '%s' "${{ secrets.SIGNING_KEY }}" | base64 -d > app/storeFile.jks
          cat > custom.properties <<EOF
          storeFile=app/storeFile.jks
          storePassword=${{ secrets.KEY_STORE_PASSWORD }}
          keyAlias=${{ secrets.ALIAS }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          EOF

      - name: Build app
        run: ./gradlew assembleRelease -PlocalPropertiesFilePath=custom.properties

      - name: Create apk env info entries, move APK
        run: python .github/build_scripts/extract_info.py

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          name: NovelDokusha v${{ env.APP_VERSION }}
          tag_name: v${{ env.APP_VERSION }}
          files: |
            ${{ env.APK_FILE_PATH_full }}
            ${{ env.APK_FILE_PATH_foss }}
